version: 2.1

orbs:
  codecov: codecov/codecov@3

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test application
          command: |
            npm run test -- --coverage
      - store_test_results:
          path: ./coverage
      - codecov/upload

workflows:
  sample:
    jobs:
      - build-and-test
