export const newDeviceActionTypes = {
  ADD_BRAND: 'ADD_BRAND',
  REMOVE_BRAND: 'REMOVE_BRAND',
  ADD_CATEGORY: 'ADD_CATEGORY',
  REMOVE_CATEGORY: 'REMOVE_CATEGORY',
  ADD_IMAGES: 'ADD_IMAGES',
  ADD_BASE_INFO: 'ADD_BASE_INFO',
  REMOVE_BASE_INFO: 'REMOVE_REMOVE_BASE_INFO',
  ADD_FEATURE_DETAILS: 'ADD_FEATURE_DETAILS',
  DELETE_FEATURE_DETAILS: 'DELETE_FEATURE_DETAILS',
  DELETE_IMAGE: 'DELETE_IMAGE',
} as const;
